gitConfig:
  core.autocrlf: "true"

tasks:
  # fix errors when installing packages inside virtualenv
  - init: sed -i "s/PIP_USER=yes/PIP_USER=no/" ~/.bashrc; source ~/.bashrc; python3 -m venv venv; source venv/bin/activate; python3 -m pip3 install --upgrade pip; pip3 install --upgrade -r requirements.dev.txt

vscode:
  extensions:
    - ms-python.python
    - stylelint.vscode-stylelint
    - foxundermoon.shell-format
    - matangover.mypy
    - streetsidesoftware.code-spell-checker
    - esbenp.prettier-vscode
    - exiasr.hadolint
    - timonwong.shellcheck

image:
  file: .gitpod.Dockerfile